### ISSUE TITLE
Problem of the training on vimeo_triplet

### ISSUE THREAD

**Issue by Mapzzone** [srcn-ivl/UPR-Net#5]
Hello, there was an issue during the training. Is this a data reading issue? Thanks！！
The error is as follows：
upr-base => val step: 1: 104/119; time: 0.00+0.27
upr-base => val step: 1: 105/119; time: 0.00+0.27
upr-base => val step: 1: 106/119; time: 0.00+0.27
upr-base => val step: 1: 107/119; time: 0.00+0.27
upr-base => val step: 1: 108/119; time: 0.00+0.27
upr-base => val step: 1: 109/119; time: 0.00+0.27
upr-base => val step: 1: 110/119; time: 0.00+0.27
upr-base => val step: 1: 111/119; time: 0.00+0.27
upr-base => val step: 1: 112/119; time: 0.00+0.27
upr-base => val step: 1: 113/119; time: 0.00+0.27
upr-base => val step: 1: 114/119; time: 0.00+0.27
upr-base => val step: 1: 115/119; time: 0.00+0.27
upr-base => val step: 1: 116/119; time: 0.00+0.27
upr-base => val step: 1: 117/119; time: 0.00+0.27
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/uprnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/amax/anaconda3/envs/uprnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/amax/anaconda3/envs/uprnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/amax/anaconda3/envs/uprnet/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/uprnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/amax/anaconda3/envs/uprnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/amax/anaconda3/envs/uprnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/amax/Desktop/wdw/UPR-Net/core/dataset.py", line 310, in __getitem__
    img0 = torch.from_numpy(img0.copy()).permute(2, 0, 1)
AttributeError: 'NoneType' object has no attribute 'copy'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1526605) of binary: /home/amax/anaconda3/envs/uprnet/bin/python
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/uprnet/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
           tools.train FAILED          
=======================================
Root Cause:
[0]:
  time: 2023-08-12_16:14:12
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 1526605)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

My running command is as follows:
`CUDA_VISIBLE_DEVICES=0,1 python3 -m torch.distributed.launch \
    --nproc_per_node=2 --master_port=10000 -m tools.train \
        --world_size=2 \
        --data_root /home/amax/Desktop/xxx/dataset/vimeo_triplet \
        --train_log_root /home/amax/Desktop/wdw/log  \
        --exp_name upr-base \
        --batch_size 32\
        --nr_data_worker 2`

**Comment by starrysky-ashin** [comment]
Hi, thanks for your interest in our work :)

In your training command, you use two GPUs, with batchsize=32 for each GPU, and thus you have batchsize=64 in total.
In our training command, we use four GPUs, with batchsize=8 for each GPU, and the total batchsize=32.

I think **maybe** in your setting, and total number of the val data cannot be divided by batchsize = 64.
You can manually set the batchsize of the `val_data`  in `tools/train.py` as a small number (for example 8). Or, you can try training with two GPUs, and set the batchsize for each GPU as 16.

**Comment by vokkko** [comment]
I change the batch_sie to 16 when i train the model used 2 gpus, but i met this question. Thus I tried to train the model for using 4 gpus with setting 8 batch_size. However it still be wrong! How can i fix this problem?

**Comment by starrysky-ashin** [comment]
> I change the batch_sie to 16 when i train the model used 2 gpus, but i met this question. Thus I tried to train the model for using 4 gpus with setting 8 batch_size. However it still be wrong! How can i fix this problem?

Do you mean you meet the same issue with Mapzzone?

Actually, I have not met this issue. Maybe there are somethong wrong with your data configuration?

**Comment by starrysky-ashin** [comment]
> I change the batch_sie to 16 when i train the model used 2 gpus, but i met this question. Thus I tried to train the model for using 4 gpus with setting 8 batch_size. However it still be wrong! How can i fix this problem?

Do you mean you meet the same issue with Mapzzone?

Actually, I have not met this issue. Maybe there are somethong wrong with your data configuration?

**Comment by vokkko** [comment]
Thanks for your proposition！However I downloaded  and unziped the datasets again, I still have the same question. : (

**Comment by starrysky-ashin** [comment]
> Thanks for your proposition！However I downloaded and unziped the datasets again, I still have the same question. : (

I think you can do a simple experiment, by using 1 GPU for training, and setting the batchsize as 1.
If in this setting, you still cannot start training, there must be something wrong with your data configuration.

**Comment by vokkko** [comment]
upr-base => val step: 1: 471/473; time: 1.06+0.14
[ WARN:0@687.559] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('./datasets/vimeo_triplet/sequences/im1.png'): can't open/read file: check file path/integrity
[ WARN:0@687.563] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('./datasets/vimeo_triplet/sequences/im2.png'): can't open/read file: check file path/integrity
[ WARN:0@687.564] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('./datasets/vimeo_triplet/sequences/im3.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/wangmingshen_1/UPR-Net-master/tools/train.py", line 389, in <module>
    train(ppl, dataset_cfg_dict, optimizer_cfg_dict)
  File "/wangmingshen_1/UPR-Net-master/tools/train.py", line 95, in train
    evaluate(ppl, step, val_data, writer_val, is_write)
  File "/wangmingshen_1/UPR-Net-master/tools/train.py", line 182, in evaluate
    for i, data in enumerate(val_data):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/wangmingshen_1/UPR-Net-master/core/dataset.py", line 310, in __getitem__
    img0 = torch.from_numpy(img0.copy()).permute(2, 0, 1)
AttributeError: 'NoneType' object has no attribute 'copy'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2584) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-26_02:52:50
  host      : df8q75jasjcll-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2584)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
***************************************************************
When I tried to use the command of --nr_data_worker 1 with just one GPU, it still broke down as the step rose to 2.

**Comment by vokkko** [comment]
Anyway, it always says that "AttributeError: 'NoneType' object has no attribute 'copy'" whether the number of Gpus I use.

**Comment by starrysky-ashin** [comment]
> Anyway, it always says that "AttributeError: 'NoneType' object has no attribute 'copy'" whether the number of Gpus I use.

“imread_('./datasets/vimeo_triplet/sequences/im3.png'): can't open/read file: check file path/integrity”

Here is the key reason. "./datasets/vimeo_triplet/sequences/im3.png" is not a true path for image file.
Please check the VimeoDataset Class in core/dataset.py, and ensure that you can correctly load the data.

By the way, "--nr_data_worker 1" does not mean "batch_size" = 1, it means one thread for data loading.

**Comment by vokkko** [comment]
well, thanks a lot. I will try to run again.

**Comment by starrysky-ashin** [comment]
> well, thanks a lot. I will try to run again.

Please tell me, when you succeed in training :)

**Comment by Q0000111** [comment]
I also encountered the same problem, no matter how I set up the batch_size, it always terminates on the second to last data batch.
upr-base => val step: 1: 3776/3783; time: 0.04+0.03
upr-base => val step: 1: 3777/3783; time: 0.04+0.03
upr-base => val step: 1: 3778/3783; time: 0.02+0.03
upr-base => val step: 1: 3779/3783; time: 0.07+0.03
upr-base => val step: 1: 3780/3783; time: 0.04+0.03
upr-base => val step: 1: 3781/3783; time: 0.03+0.03
Traceback (most recent call last):
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\paper\UPR-Net-master\tools\train.py", line 391, in <module>
    train(ppl, dataset_cfg_dict, optimizer_cfg_dict)
  File "D:\paper\UPR-Net-master\tools\train.py", line 97, in train
    evaluate(ppl, step, val_data, writer_val, is_write)
  File "D:\paper\UPR-Net-master\tools\train.py", line 184, in evaluate
    for i, data in enumerate(val_data):
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\paper\UPR-Net-master\core\dataset.py", line 310, in __getitem__
    img0 = torch.from_numpy(img0.copy()).permute(2, 0, 1)
AttributeError: 'NoneType' object has no attribute 'copy'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6464) of binary: D:\codesoftware\anaconda3\envs\uprnet\python3.exe
Traceback (most recent call last):
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\distributed\run.py", line 713, in run
    )(*cmd_args)
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\codesoftware\anaconda3\envs\uprnet\lib\site-packages\torch\distributed\launcher\api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
tools.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-26_13:28:28
  host      : DESKTOP-P786LLV.nju.edu.cn
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6464)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Plumess** [comment]
> UPR-Base => Val 步长：1：471/473;时间：1.06+0.14 [ WARN：0@687.559] 全局 /io/opencv/modules/imgcodecs/src/loadsave.cpp （239） findDecoder imread_（'./datasets/vimeo_triplet/sequences/im1.png'）：无法打开/读取文件：检查文件路径/完整性 [ WARN：0@687.563] 全局 /io/opencv/modules/imgcodecs/src/loadsave.cpp （239） findDecoder imread_（'./datasets/vimeo_triplet/sequences/im2.png'）：无法打开/读取文件：检查文件路径/完整性[ WARN：0@687.564] 全局 /io/opencv/modules/imgcodecs/src/loadsave.cpp （239） findDecoder imread_（'./datasets/vimeo_triplet/sequences/im3.png'）：无法打开/读取文件：检查文件路径/完整性 回溯（最近一次调用最后一次）： 文件“/usr/lib/python3.6/runpy.py”，第 193 行，_run_module_as_main“**main**”， mod_spec） 文件“/usr/lib/python3.6/runpy.py”，第 85 行，在 _run_code exec（code， run_globals） 文件 “/wangmingshen_1/UPR-Net-master/tools/train.py”，第 389 行，在 train（ppl， dataset_cfg_dict， optimizer_cfg_dict） 文件 “/wangmingshen_1/UPR-Net-master/tools/train.py”，第 95 行，在 train evaluate（ppl， step， val_data， writer_val， is_write） 文件 “/wangmingshen_1/UPR-Net-master/tools/train.py”，第 182 行，在 evaluate for i 中，在 enumerate（val_data） 中的数据：文件 “/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py”，第 521 行，**在下一个** data = self._next_data（） 文件 “/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py”，第 1203 行，在 _next_data 中返回 self._process_data（data） 文件 “/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py”，第 1229 行_process_data，在 data.reraise（） 中文件“/usr/local/lib/python3.6/dist-packages/torch/_utils.py”，第 434 行，在 reraise raise exception AttributeError： Caught AttributeError in DataLoader worker process 0 中。原始回溯（最近一次调用最后一次）： 文件“/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py”，第 287 行，在 _worker_loop 中 data = fetcher.fetch（index） 文件 “/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py”，第 49 行，在 fetch 中 data = [self.dataset[idx] for idx in possibly_batched_index]文件“/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py”，第 49 行，data = [self.dataset[idx] for idx in possibly_batched_index] 文件“/wangmingshen_1/UPR-Net-master/core/dataset.py”，第 310 行，**getitem** img0 = torch.from_numpy（img0.copy（））.permute（2， 0， 1） AttributeError：“NoneType”对象没有属性“copy”
> 
> # 错误：torch.distributed.elastic.multiprocessing.api：失败（退出代码：1） local_rank：0（pid：2584）二进制文件：/usr/bin/python3 回溯（最近一次调用最后一次）：
> 文件“/usr/lib/python3.6/runpy.py”，第 193 行，_run_module_as_main
> “**main**”，mod_spec） 文件“/usr/lib/python3.6/runpy.py”，第 85 行，在 _run_code
> exec（code， run_globals）
> 
> 文件“/usr/local/lib/python3.6
> /dist-packages/torch/distributed/launch.py”中， 第 193 行，在 main（） 中 文件“/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py”，第 189 行，在
> 主 launch（args） 中 文件“/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py”，第 174 行，在启动运行中 （args） 文件 “/usr/local/lib/python3.6/dist-packages/torch/distributed/run.py”，第 713 行，在
> 运行
> 中 ）（*cmd_args）
> 
> 
> 
> 
> 文件“/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py”，第 131 行，**在调用**
> 返回中 launch_agent（self._config， self._entrypoint， list（args））
> 文件“/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py”，第 261 行，在 launch_agent failures=
> result.failures，
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError：
> ## tools.train 失败
> ## 失败次数：
> <NO_OTHER_FAILURES>
> 根本原因（第一次观察到的故障）： [0]： 时间 ： 2023-09-26_02：52：50 主机 ： df8q75jasjcll-0 排名 ： 0 （local_rank： 0） 退出代码 ： 1 （PID： 2584） error_file： <N/A> 回溯 ： 要启用回溯，请参阅： https://pytorch.org/docs/stable/elastic/errors.html
> 
> 当我尝试仅使用一个 GPU 使用 --nr_data_worker 1 的命令时，当步长上升到 2 时，它仍然崩溃了。

Hello,

I noticed that you encountered a similar issue with the `VimeoDataset` class that I faced recently. The problem arises when there are empty lines in `tri_testlist.txt` and `tri_trainlist.txt`. This causes incorrect file path construction in the `getimg` method of the `VimeoDataset` class.

### Solution:

The `VimeoDataset` class constructs image paths based on the contents of `tri_testlist.txt` and `tri_trainlist.txt`. Therefore, it is crucial that these files do not contain any empty lines. Each line in these files should represent a valid relative path to the image sequences.

To resolve the issue, ensure that `tri_testlist.txt` and `tri_trainlist.txt`:

- Contain no empty lines.
- Each line accurately reflects the relative path to the respective image sequences in the `sequences` directory.

By ensuring the integrity of these text files, the `VimeoDataset` class should function correctly, and images will be loaded without errors.

Best regards,

Plumess

**Comment by Henrysu1998** [comment]
> > UPR-Base => Val 步长：1：471/473;时间：1.06+0.14 [ WARN：0@687.559] 全局 /io/opencv/modules/imgcodecs/src/loadsave.cpp （239） findDecoder imread_（'./datasets/vimeo_triplet/sequences/im1.png'）：无法打开/读取文件：检查文件路径/完整性 [ WARN：0@687.563] 全局 /io/opencv/modules/imgcodecs/src/loadsave.cpp （239） findDecoder imread_（'./datasets/vimeo_triplet/sequences/im2.png'）：无法打开/读取文件：检查文件路径/完整性[ WARN：0@687.564] 全局 /io/opencv/modules/imgcodecs/src/loadsave.cpp （239） findDecoder imread_（'./datasets/vimeo_triplet/sequences/im3.png'）：无法打开/读取文件：检查文件路径/完整性 回溯（最近一次调用最后一次）： 文件“/usr/lib/python3.6/runpy.py”，第 193 行，_run_module_as_main“**main**”， mod_spec） 文件“/usr/lib/python3.6/runpy.py”，第 85 行，在 _run_code exec（code， run_globals） 文件 “/wangmingshen_1/UPR-Net-master/tools/train.py”，第 389 行，在 train（ppl， dataset_cfg_dict， optimizer_cfg_dict） 文件 “/wangmingshen_1/UPR-Net-master/tools/train.py”，第 95 行，在 train evaluate（ppl， step， val_data， writer_val， is_write） 文件 “/wangmingshen_1/UPR-Net-master/tools/train.py”，第 182 行，在 evaluate for i 中，在 enumerate（val_data） 中的数据：文件 “/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py”，第 521 行，**在下一个** data = self._next_data（） 文件 “/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py”，第 1203 行，在 _next_data 中返回 self._process_data（data） 文件 “/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py”，第 1229 行_process_data，在 data.reraise（） 中文件“/usr/local/lib/python3.6/dist-packages/torch/_utils.py”，第 434 行，在 reraise raise exception AttributeError： Caught AttributeError in DataLoader worker process 0 中。原始回溯（最近一次调用最后一次）： 文件“/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py”，第 287 行，在 _worker_loop 中 data = fetcher.fetch（index） 文件 “/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py”，第 49 行，在 fetch 中 data = [self.dataset[idx] for idx in possibly_batched_index]文件“/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py”，第 49 行，data = [self.dataset[idx] for idx in possibly_batched_index] 文件“/wangmingshen_1/UPR-Net-master/core/dataset.py”，第 310 行，**getitem** img0 = torch.from_numpy（img0.copy（））.permute（2， 0， 1） AttributeError：“NoneType”对象没有属性“copy”
> > # 错误：torch.distributed.elastic.multiprocessing.api：失败（退出代码：1） local_rank：0（pid：2584）二进制文件：/usr/bin/python3 回溯（最近一次调用最后一次）：
> > 文件“/usr/lib/python3.6/runpy.py”，第 193 行，_run_module_as_main
> > “**main**”，mod_spec） 文件“/usr/lib/python3.6/runpy.py”，第 85 行，在 _run_code
> > exec（code， run_globals）
> > 文件“/usr/local/lib/python3.6
> > /dist-packages/torch/distributed/launch.py”中， 第 193 行，在 main（） 中 文件“/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py”，第 189 行，在
> > 主 launch（args） 中 文件“/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py”，第 174 行，在启动运行中 （args） 文件 “/usr/local/lib/python3.6/dist-packages/torch/distributed/run.py”，第 713 行，在
> > 运行
> > 中 ）（*cmd_args）
> > 文件“/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py”，第 131 行，**在调用**
> > 返回中 launch_agent（self._config， self._entrypoint， list（args））
> > 文件“/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py”，第 261 行，在 launch_agent failures=
> > result.failures，
> > torch.distributed.elastic.multiprocessing.errors.ChildFailedError：
> > ## tools.train 失败
> > ## 失败次数：
> > <NO_OTHER_FAILURES>
> > 根本原因（第一次观察到的故障）： [0]： 时间 ： 2023-09-26_02：52：50 主机 ： df8q75jasjcll-0 排名 ： 0 （local_rank： 0） 退出代码 ： 1 （PID： 2584） error_file： <N/A> 回溯 ： 要启用回溯，请参阅： https://pytorch.org/docs/stable/elastic/errors.html
> > 当我尝试仅使用一个 GPU 使用 --nr_data_worker 1 的命令时，当步长上升到 2 时，它仍然崩溃了。
> 
> Hello,
> 
> I noticed that you encountered a similar issue with the `VimeoDataset` class that I faced recently. The problem arises when there are empty lines in `tri_testlist.txt` and `tri_trainlist.txt`. This causes incorrect file path construction in the `getimg` method of the `VimeoDataset` class.
> 
> ### Solution:
> The `VimeoDataset` class constructs image paths based on the contents of `tri_testlist.txt` and `tri_trainlist.txt`. Therefore, it is crucial that these files do not contain any empty lines. Each line in these files should represent a valid relative path to the image sequences.
> 
> To resolve the issue, ensure that `tri_testlist.txt` and `tri_trainlist.txt`:
> 
> * Contain no empty lines.
> * Each line accurately reflects the relative path to the respective image sequences in the `sequences` directory.
> 
> By ensuring the integrity of these text files, the `VimeoDataset` class should function correctly, and images will be loaded without errors.
> 
> Best regards,
> 
> Plumess
I met this issue. And this answer is right!

**Comment by Henrysu1998** [comment]
I met this issue before. And this answer is the right solution. [Plumess](https://github.com/Plumess)
